name: Check ECR Tag Exist
inputs:
  ecr_repo_name:
    default: ""
  docker_image_tag:
    default: ""
  purpose:
    default: ""
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "checking ecr tag..."

    - name: Check Input Existence
      shell: bash
      run: |
        tags=$(aws ecr list-images --repository-name ${{ inputs.ecr_repo_name }} | jq '.imageIds' | jq -r '.[]' | jq -r .imageTag)
        for tag in $tags
          do
            if [ $tag ==  ${{ inputs.docker_image_tag }} ]
            then
              exist=1
              break
            else
              exist=0
            fi
          done
      
        if [ $exist == 1 ] && [ "${{ inputs.if_purpose }}" == "build" ]; then
          echo "same tag already exist : $tag"
          echo "FAIL_MESSAGE=same tag already exist : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        fi
          
        if [ $exist == 1 ] && [ "${{ inputs.purpose }}" == "deploy" ]; then
          echo "tag is valid : ${{ inputs.docker_image_tag }}"
          echo "FAIL_MESSAGE=tag is valid, but for other reason : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
        fi

        if [ $exist == 0 ] && [ "${{ inputs.purpose }}" == "build" ]; then
          echo "tag is valid : ${{ inputs.docker_image_tag }}"
          echo "FAIL_MESSAGE=tag is valid, but for other reason : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
        fi

        if [ $exist == 0 ] && [ "${{ inputs.purpose }}" == "deploy" ]; then
          echo "can not find input tag : $tag"
          echo "FAIL_MESSAGE=can not find input tag : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        fi
