name: Check ECR Tag Exist
inputs:
  ecr_repo_name:
    default: ""
  docker_image_tag:
    default: ""
  if_exist:
    default: "continue"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "checking ecr tag..."

    - name: Check Input Existence
      shell: bash
      run: |
        tags=$(aws ecr list-images --repository-name ${{ inputs.ecr_repo_name }} | jq '.imageIds' | jq -r '.[]' | jq -r .imageTag)
        for tag in $tags
          do
            if [ $tag ==  ${{ inputs.docker_image_tag }} ]
            then
              exist=1
              break
            else
              exist=0
            fi
          done
        
        if [ $exist == 1 ] && [ "${{ inputs.if_exist }}" == "continue" ]; then
          echo "same tag already exist : $tag"
          echo "FAIL_MESSAGE=same tag already exist : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        elif [ $exist == 0 ] && [ "${{ inputs.if_exist }}" == "break" ]; then
          echo "can not find input tag : $tag"
          echo "FAIL_MESSAGE=can not find input tag : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        fi

        # if [ $exist == 1 ] && [ "${{ inputs.if_exist }}" == "continue" ]; then
          
        if [ $exist == 1 ] && [ "${{ inputs.if_exist }}" == "break" ]; then
          echo "same tag already exist : $tag"
          echo "FAIL_MESSAGE=same tag already exist : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        fi

        # if [ $exist == 0 ] && [ "${{ inputs.if_exist }}" == "continue" ]; then

        if [ $exist == 0 ] && [ "${{ inputs.if_exist }}" == "break" ]; then
           echo "can not find input tag : $tag"
          echo "FAIL_MESSAGE=can not find input tag : ${{ inputs.docker_image_tag }}" >> $GITHUB_ENV
          exit 1
        fi
