name: Check ECR Tag Exist
inputs:
  ecr_repo_name:
    default: ""
  docker_image_tag:
    default: ""
  exist:
    default: "yes"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "checking ecr tag..."
    - shell: bash
      if: ${{ inputs.exist == yes }}
      run: |
        echo "input exist is yes"
        echo ${{ inputs.exist }}
    - shell: bash
      if: ${{ inputs.exist == no }}
      run: |
        echo "input exist is no"
        echo ${{ inputs.exist }}
